steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/aozora/web:$COMMIT_SHA', '-f', 'web/Dockerfile', 'web']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/aozora/web:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aozora-pages-web'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/aozora/web:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - 'ALGOLIA_APP_ID=$$ALGOLIA_APP_ID,ALGOLIA_SEARCH_KEY=$$ALGOLIA_SEARCH_KEY'
    secretEnv: ['ALGOLIA_APP_ID', 'ALGOLIA_SEARCH_KEY']

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/aozora/web:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/ALGOLIA_APP_ID/versions/latest
      env: 'ALGOLIA_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/ALGOLIA_SEARCH_KEY/versions/latest
      env: 'ALGOLIA_SEARCH_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
