steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', '${_DOCKERFILE}', '-t', '${_IMAGE}', '.']

substitutions:
  _DOCKERFILE: Dockerfile
  _IMAGE: ''

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_IMAGE}'
