"""Generate aozora_data/sjis_to_utf8/gaiji_table.py from jisx0213-2004-std.txt.

The mapping file is distributed with the nkf project:
  https://osdn.net/projects/nkf/

To obtain it:
  1. Download the nkf source archive from the URL above.
  2. Extract jisx0213-2004-std.txt from the archive root.

File format (tab-separated, # comments ignored):
  <key>\\t<codepoint(s)>[\\t<comment>]

  key          — JIS X 0213 GL-encoded key, e.g. "3-2121" (Plane 1) or "4-2121" (Plane 2)
  codepoint(s) — one or more U+XXXX values joined by '+', e.g. "U+3000" or "U+304B+U+309A"

Usage:
  python scripts/generate_gaiji_table.py jisx0213-2004-std.txt
  python scripts/generate_gaiji_table.py jisx0213-2004-std.txt --output path/to/gaiji_table.py
"""

import argparse
import json
import re
import sys
from pathlib import Path

OUTPUT_PATH = (
    Path(__file__).parent.parent / "aozora_data" / "sjis_to_utf8" / "gaiji_table.py"
)


def parse_codepoints(cp_field: str) -> str:
    """Extract U+XXXX code points from a field and return the corresponding string.

    Examples:
        "U+3000"           -> "　"
        "U+304B+U+309A"    -> "か゚"
    """
    tokens = re.findall(r"U\+([0-9A-Fa-f]+)", cp_field)
    if not tokens:
        raise ValueError(f"no U+XXXX codepoints found in {cp_field!r}")
    return "".join(chr(int(t, 16)) for t in tokens)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("input", help="Path to jisx0213-2004-std.txt")
    parser.add_argument(
        "--output",
        default=str(OUTPUT_PATH),
        help=f"Output path (default: {OUTPUT_PATH})",
    )
    args = parser.parse_args()

    entries: dict[str, str] = {}
    errors = 0

    with open(args.input, encoding="utf-8") as f:
        for lineno, line in enumerate(f, 1):
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue

            # Fields are whitespace-separated; third field onward is a comment.
            parts = line.split(maxsplit=2)
            if len(parts) < 2:
                print(f"warning: line {lineno}: too few fields, skipping: {line!r}", file=sys.stderr)
                errors += 1
                continue

            key = parts[0]
            cp_field = parts[1]

            # Lines where the codepoint field is '#' have no Unicode mapping defined.
            if cp_field.startswith("#"):
                continue

            try:
                value = parse_codepoints(cp_field)
            except ValueError as e:
                print(f"warning: line {lineno}: {e}, skipping", file=sys.stderr)
                errors += 1
                continue

            entries[key] = value

    output_path = Path(args.output)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# This file is auto-generated by scripts/generate_gaiji_table.py\n")
        f.write("# Do not edit manually.\n")
        f.write("\n")
        f.write("# ruff: noqa: RUF001\n")
        f.write("GAIJI_TABLE = {\n")
        for key, value in entries.items():
            f.write(f"    {key!r}: {json.dumps(value, ensure_ascii=False)},\n")
        f.write("}\n")

    print(f"wrote {len(entries)} entries to {output_path}")
    if errors:
        print(f"{errors} line(s) skipped due to errors", file=sys.stderr)


if __name__ == "__main__":
    main()
